//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TomOkna
{
    using System;
    using System.Collections.Generic;
    
    public partial class Appliances
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Appliances()
        {
            this.Orders = new HashSet<Orders>();
        }
    
        public int id_Appliance { get; set; }
        public string Model { get; set; }
        public int ApplianceType_FK { get; set; }
        public System.DateTime DateOfManufacturere { get; set; }
        public int GuaranteePeriodDay { get; set; }
        public int Manufacturer_FK { get; set; }
        public decimal Price { get; set; }
        public string AboutInformation { get; set; }
    
        public virtual ApplianceType ApplianceType { get; set; }
        public virtual Manufacturers Manufacturers { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Orders> Orders { get; set; }
    }
}
