//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TomOkna
{
    using System;
    using System.Collections.Generic;
    
    public partial class Orders
    {
        public int id_Orders { get; set; }
        public int Seller_FK { get; set; }
        public int Client_FK { get; set; }
        public int Appliance_FK { get; set; }
        public System.DateTime OrderDate { get; set; }
        public decimal Price { get; set; }
        public string Status { get; set; }
    
        public virtual Appliances Appliances { get; set; }
        public virtual Clients Clients { get; set; }
        public virtual Seller Seller { get; set; }
    }
}
